<a href="https://colab.research.google.com/github/bwilli2086/data_analytics/blob/main/Python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
np_city=np.array(['NYC','LA','Houston','Miami'])
#np_city.ndim
#np_city.shape
#np_city.size
np_city.dtype



dtype('<U7')

In [10]:
import numpy as np
np_city_state=np.array([['NYC','LA','Houston','Miami'],['NY','CA','TX','FL']])
#np_city_state.ndim
#np_city_state.shape
#np_city_state.size
#np_city_state.dtype


8

In [11]:
first_trail=[10,15,17,26]
second_trail=[12,11,21,24]
np_ftc=np.array(first_trail)
np_stc=np.array(second_trail)
np_ftc+np_stc

array([22, 26, 38, 50])

In [16]:
cyclist_time=np.array([[10,15,17,26],[12,11,21,24]])
ftc_time=cyclist_time[0]
ftc_times=cyclist_time[0,0]
stc_time=cyclist_time[1]
stc_times=cyclist_time[1,0]
print(ftc_time)
print(ftc_times)
print(stc_time)
print(stc_times)




[10 15 17 26]
10
[12 11 21 24]
12


In [21]:
test_score=np.array([[81,71,57,63],[54,61,87,45]])
passing_score=test_score>60
passing_score
#test_score[passing_score]



[81 71 63 61 87]


In [36]:
NYC_Bor=np.array(['Manhattan','Queens','Brooklyn','Staten Island','Bronx'])
#NYC_Bor
bor_nyc=NYC_Bor
bor_in_nyc=bor_nyc.view()
bor_in_nyc
#NYC_Bor is bor_in_nyc
#len(bor_in_nyc)
#bor_in_nyc[3]

array(['Manhattan', 'Queens', 'Brooklyn', 'Staten Island', 'Bronx'],
      dtype='<U13')

In [42]:
np_sqrt=np.sqrt([2,4,9,16])
np_sqrt
from numpy import pi
#np.cos(0)
#np.sin(pi/2)
#np.cos(pi)
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])
#np.exp([0,1,5])


array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [44]:
array_a=np.array([2,3,5,9])
array_b=np.array([0.3,0.3,0.3,0.3])

#array_a*array_b
scalar_c=0.3
array_a*scalar_c

array([0.6, 0.9, 1.5, 2.7])

In [45]:
inverse_array=np.array([[10,20],[15,25]])
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [48]:
trace_array=np.array([[10,20],[22,31]])
np.trace(trace_array)

41